name: "Beirut Hold'em"
favicon: null
layout_spectrum: 0.03954943502321839
typography_spectrum: 0.5250175381079316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3a3730'
    - '#d6d7d2'
    - '#a4a5a0'
    - '#5c5952'
    - '#7e7f7a'
  brandStrength: 0.5033180078025907
  lightness: 0.15116711636073887
  saturation: 0.16943085053935647
  rhythmicContrast: 0.823383318958804
purpose: []
