name: "Beirut Hold'em"
favicon: null
layout_spectrum: 0.03954943502321839
typography_spectrum: 0.5250175381079316
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: "beirut hold'em"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3a3730'
    - '#d6d7d2'
    - '#a4a5a0'
    - '#5c5952'
    - '#7e7f7a'
  brandStrength: 1
  lightness: 0.1511671163607389
  saturation: 0.1694308505393565
  rhythmicContrast: 0.823383318958804
purpose: []
